Local Storageを作成 first-commit
OzawaSachio/sachi-frontend-basic-2022-todoapp pull request #13
Opened 2023-09-10 07:00 UTC by OzawaSachio

2023-09-11 07:25 UTC, mkazu0428 commented
taskListの内容が変わるたびに、ブラウザに記憶させる"taskData"の内容を更新する機能は書けていると思います。

あとは、初回レンダリング時のuseEffectに問題があると思います。
ヒント
●このコードだとdataという関数を宣言しているに過ぎないので、初回にブラウザに保存されている"taskData"の内容を取り出すことはできません。（おそらく！！）

2023-09-16 08:21 UTC, higashiji2000 requested changes

2023-09-16 08:21 UTC, higashiji2000 commented on src/components/Organisms/TodoCard/index.jsx
> +    setTaskList(data);
![image](https://github.com/OzawaSachio/sachi-frontend-basic-2022-todoapp/assets/83479175/ce293685-80b0-4834-921c-44f6ee5dd37e)

一番最初にこのサイトに訪れたタイミングだとlocalStrageにデータが存在しないので `taskList` に `null` が入ります。
そのため、 `taskElements` を宣言している以下の部分で `null` には `map` メソッドが存在しないよ、と怒られているのが画像の状態です。

```jsx
  const taskElements = taskList.map((task, index) => {
```

```suggestion
    const data = JSON.parse(localStorage.getItem("taskData")) ?? [];
    setTaskList(data);
```
このように [null合体演算子](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) を使うと、localStrageが空であっても対応可能です。

2023-09-16 08:22 UTC, higashiji2000 commented on src/components/Organisms/TodoCard/index.jsx
> +    setTaskList(data);
挙動を確かめるためには、シークレットウインドウでstorybookを開くのがおすすめです。
（localStrageが空っぽの状態で開くことが）

2023-09-23 12:52 UTC, OzawaSachio commented on src/components/Organisms/TodoCard/index.jsx
> +    setTaskList(data);
> ![image](https://user-images.githubusercontent.com/83479175/268437114-ce293685-80b0-4834-921c-44f6ee5dd37e.png)
> 
> 一番最初にこのサイトに訪れたタイミングだとlocalStrageにデータが存在しないので `taskList` に `null` が入ります。 そのため、 `taskElements` を宣言している以下の部分で `null` には `map` メソッドが存在しないよ、と怒られているのが画像の状態です。
> 
> ```js
>   const taskElements = taskList.map((task, index) => {
> ```
> 
> このように [null合体演算子](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) を使うと、localStrageが空であっても対応可能です。

「(localStorage.getItem("taskData")) ?? []」と記述した所「SyntaxError: Unexpected token o in JSON at position 1」というエラー文が出てきてきた為、「(localStorage.getItem("taskData") ?? [])」と記述して修正しました。
この修正によって別の不具合が生じていないかレビューしていただけると幸いです。

2023-09-23 14:51 UTC, higashiji2000 requested changes

2023-09-23 14:51 UTC, higashiji2000 commented on src/components/Organisms/TodoCard/index.jsx
> +    const data = JSON.parse(localStorage.getItem("taskData") ?? []);
`SyntaxError: Unexpected token o in JSON at position 1` は、現状の実装に起因するものだと思います。

![image](https://github.com/OzawaSachio/sachi-frontend-basic-2022-todoapp/assets/83479175/2ec5b1c5-bf03-4f32-b8ac-86c3c8bed541)
画像に示したように、 `[]` を `JSON.parse()` に入れると unexpected Json Input のエラーが出てしまいます。

初回の表示の際は `taskData` が localStrageに存在しないため `JSON.parse([])` となり、上記のエラーが出てしまうわけです。

```suggestion
    const data = JSON.parse(localStorage.getItem("taskData")) ?? [];
```

提案したように修正して、シークレットウインドウで開いてみてください。
おそらくエラーが出なくなると思います。

（二回目以降は46行目の記述によりオブジェクトが入るため、エラーが出なくなります。）

2023-09-23 14:53 UTC, higashiji2000 commented on src/components/Organisms/TodoCard/index.jsx
> +    const data = JSON.parse(localStorage.getItem("taskData") ?? []);
Chromatic が エラーになっているのも、この修正を入れれば直るかと！

2023-09-24 05:48 UTC, haruchu commented
挙動問題なさそうです！
LGTM🙆‍♂️

2023-09-24 05:48 UTC, haruchu approved these changes

2023-09-25 12:21 UTC, merged