Alertの実装をとりあえず作ったが未完成でエラーも出ている
OzawaSachio/sachi-frontend-basic-2022-todoapp pull request #14
Opened 2023-11-19 06:00 UTC by OzawaSachio

2023-11-21 21:43 UTC, ssshun3 commented
エラー文のReact is not definedはreactをimportしていないだけなので該当するファイルでimportしてあげてください。

2023-11-21 21:44 UTC, ssshun3 commented on src/components/Organisms/AlertManager/index.jsx
> +  AlertHandlerContext.setAlert("message");
エラー文を見るに無限ループが起こっているようです。
AlertManager コンポーネントは、アラートの状態を管理するためのものであり、ここでsetAlertを呼び出してアラートの状態を更新します。しかし、このコードでは毎回setAlertを呼び出しています(呼び出すための条件が存在しない)。そのため無限ループが発生しているのだと思います。

1. AlertManager がレンダリングされる。

1. レンダリング中に setAlert が呼び出され、アラートの状態が更新される。
2. 状態が更新されると、AlertManager を再レンダリングする。
3. 再レンダリング時にまた setAlert が呼び出され、状態が再び更新される。
4. このプロセスが無限に繰り返されるため、無限ループが発生する。

そのためsetAlertを呼び出すための条件(useEffectなどを用いて)を設定してください。

2023-12-25 04:37 UTC, higashiji2000 requested changes
<img width="376" alt="image" src="https://github.com/OzawaSachio/sachi-frontend-basic-2022-todoapp/assets/83479175/f028691a-1d53-4376-b570-2ac210e1a588">
  
> [!IMPORTANT]
> 画面幅が小さいときにAlertの表示位置がおかしいので、修正をお願いします。

<img width="1512" alt="image" src="https://github.com/OzawaSachio/sachi-frontend-basic-2022-todoapp/assets/83479175/12d19f76-aac4-4622-8681-073870258f11">

> [!IMPORTANT]
> Github Pagesだと画面幅ほぼいっぱいに伸びてしまうので、お手本を参考にmax-widthを設定してください。
> url: https://ozawasachio.github.io/sachi-frontend-basic-2022-todoapp/
> お手本: https://shinonome.io/frontend-basic-2022-todoapp/

2023-12-31 05:19 UTC, OzawaSachio commented
> <img alt="image" width="376" src="https://private-user-images.githubusercontent.com/83479175/292709039-f028691a-1d53-4376-b570-2ac210e1a588.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5OTk3OTQsIm5iZiI6MTcwMzk5OTQ5NCwicGF0aCI6Ii84MzQ3OTE3NS8yOTI3MDkwMzktZjAyODY5MWEtMWQ1My00Mzc2LWI1NzAtMmFjMjEwZTFhNTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA1MTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YzY5MGYxNWU4MGU5YjExMzUxMDJkZTNhNmY5OTQ3MmJiYTFjMmVlYzljZGQwZGQ1ODUwYzRlNzYzYTA2MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.voq3iACQa1rYsRnoZRtJixV0WFDCFFbHmIrXP-4KO2Y">
> Important
> 
> 画面幅が小さいときにAlertの表示位置がおかしいので、修正をお願いします。
> 
> <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/83479175/292709106-12d19f76-aac4-4622-8681-073870258f11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5OTk3OTQsIm5iZiI6MTcwMzk5OTQ5NCwicGF0aCI6Ii84MzQ3OTE3NS8yOTI3MDkxMDYtMTJkMTlmNzYtYWFjNC00NjIyLTg2ODEtMDczODcwMjU4ZjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA1MTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNTNhYTQ5NWY3YzUyYmJiMDI2NzkwMTE3YzJmOTFjNjc4MTZlNWFiMWZhZDc1MDRjNTkzMWQ2ZjgwNWFlYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wanbwcKQp6QFakEIfuGqRtc-C3-OQhxKVtjAaxs1wtA">
> Important
> 
> Github Pagesだと画面幅ほぼいっぱいに伸びてしまうので、お手本を参考にmax-widthを設定してください。 url: https://ozawasachio.github.io/sachi-frontend-basic-2022-todoapp/ お手本: https://shinonome.io/frontend-basic-2022-todoapp/

<img width="900" alt="画面幅が小さい時のAlertの位置" src="https://github.com/OzawaSachio/sachi-frontend-basic-2022-todoapp/assets/105160901/55edc84f-f3c8-4a6c-bea1-41e63e0872ea">
私のPC上だと画面幅が小さい時のAlertの位置は正常なのですが、どのように対応すればよいでしょうか。

2023-12-31 06:13 UTC, OzawaSachio commented
> https://63a53d80157f2555225e5cba-ntfcayqdxp.chromatic.com/?path=/story/pages-mainpage--default

一番上にあるchromaticのリンクを更新しました。

2023-12-31 06:54 UTC, OzawaSachio commented
↑の修正は、二次レビュー依頼提出時点で既にあったAlertの位置に関するコードを一度消去してしまった為に同じコードを再度pushしただけですので、二次レビュー依頼時点でchromaticやgithub pagesの表示がローカルブランチと異なる表示になっていたこととは関係ないと思われます。

2024-01-05 08:09 UTC, higashiji2000 requested changes

2024-01-05 08:09 UTC, Higashiji commented on src/components/Pages/MainPage/index.jsx
> +  max-width: 400px;
```suggestion
  max-width: 500px;
```
お手本やFigmaと同様500pxとするとGoogです！

2024-01-05 08:09 UTC, higashiji2000 commented on src/components/Atoms/Alert/index.jsx
> +  display: flex;
```suggestion
const AlertWrapper = styled.div`
  z-index: 1000;
  width: 100%;
  display: flex;
```
こうすると、ボタンのテキストがAlertより手前に来ている問題を解決できます。

2024-01-11 15:50 UTC, higashiji2000 approved these changes
LGTM✨

2024-01-12 02:26 UTC, merged